name    'puppet-apt_mirror'
version '1.0.2'
source 'https://github.com/greenaar/puppet-apt_mirror.git'
author 'Various'
license 'Apache 2.0'
summary 'apt-mirror handler for Puppet'
description 'This module provides a handler for apt-mirror'
project_page 'https://github.com/greenaar/puppet-apt_mirror'
dependency 'puppetlabs/concat'
